デバイスを実装しました
tsubasa0105/book_app pull request #3
Opened 2019-02-07 08:06 UTC by tsubasa0105

# 変更内容
- デバイスを実装し、ユーザー認証機能を追加
- ログインやログアウト時の表示を日本語や英語に対応

2019-02-07 10:07 UTC, komagata requested changes

2019-02-07 10:07 UTC, komagata commented on Gemfile
> +
不要な空欄があるように思います。

2019-02-07 10:07 UTC, komagata commented on test/fixtures/users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
不要なファイルは含めないようにしてください。

2019-02-07 10:07 UTC, komagata commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/plataformatec/devise/wiki/I18n
devise-i18nを使っている場合、gemに含まれているのでこのファイルを自分のアプリに置く必要はありません。

2019-02-08 03:44 UTC, tsubasa0105 commented on Gemfile
> +
不要な空欄を削除いたしました。

2019-02-08 03:46 UTC, tsubasa0105 commented on test/fixtures/users.yml
> +# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
追跡対象から外し、gitignoreに記載しました。

2019-02-08 03:48 UTC, tsubasa0105 commented on config/locales/devise.en.yml
> +# Additional translations at https://github.com/plataformatec/devise/wiki/I18n
アプリから削除いたしました。

2019-02-08 04:45 UTC, komagata requested changes
言われたことをそのままやるだけでなく、指摘された内容を理解して、他にも同じミスを犯しているところがないかチェックしてから提出するようにしてくださいー。

レビューワーもすべての空行をしてきすることはしないです。

2019-02-08 04:45 UTC, komagata commented on config/locales/devise.ja.yml
> +ja:
devise-i18nを使っている場合、gemに含まれているのでこのファイルを自分のアプリに置く必要はありません。

2019-02-08 04:45 UTC, komagata commented on config/locales/en.yml
> +
不要な空欄があるように思います。

2019-02-08 04:45 UTC, komagata commented on config/locales/ja.yml
> +
不要な空欄があるように思います。

2019-02-08 04:45 UTC, komagata commented on test/models/user_test.rb
> +require 'test_helper'
不要なファイルは含めないようにしてください。

2019-02-11 05:43 UTC, tsubasa0105 commented on config/locales/devise.ja.yml
> +ja:
確認、そして理解至らず申し訳ありません。gemの機能から必要ないと理解しdevise.ja.ymlを削除いたしました。

2019-02-11 05:44 UTC, tsubasa0105 commented on config/locales/en.yml
> +
不要な空欄を削除いたしました。

2019-02-11 05:44 UTC, tsubasa0105 commented on config/locales/ja.yml
> +
不要な空欄を削除いたしました。

2019-02-11 05:44 UTC, tsubasa0105 commented on test/models/user_test.rb
> +require 'test_helper'
追跡から外し、gitignoreに記載しました。

2019-02-12 03:25 UTC, komagata approved these changes

2019-02-12 04:04 UTC, merged